apply shfmt for all scripts
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

diff --git a/hack/validate/vendor b/hack/validate/vendor
--- a/hack/validate/vendor
+++ b/hack/validate/vendor
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
 
-export SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+export SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 source "${SCRIPTDIR}/.validate"
 
-validate_vendor_diff(){
+validate_vendor_diff() {
 	IFS=$'\n'
-	files=( $(validate_diff --diff-filter=ACMR --name-only -- 'vendor.conf' 'vendor/' || true) )
+	files=($(validate_diff --diff-filter=ACMR --name-only -- 'vendor.conf' 'vendor/' || true))
 	unset IFS
 
 	if [ ${#files[@]} -gt 0 ]; then
@@ -34,16 +34,16 @@ validate_vendor_diff(){
 # 1. make sure all the vendored packages are used
 # 2. make sure all the packages contain license information (just warning, because it can cause false-positive)
 validate_vendor_used() {
-	pkgs=$(mawk '/^[a-zA-Z0-9]/ { print $1 }' < vendor.conf)
+	pkgs=$(mawk '/^[a-zA-Z0-9]/ { print $1 }' <vendor.conf)
 	for f in $pkgs; do
-	if ls -d vendor/$f  > /dev/null 2>&1; then
-		found=$(find vendor/$f -iregex '.*LICENSE.*' -or -iregex '.*COPYRIGHT.*' -or -iregex '.*COPYING.*' | wc -l)
-		if [ $found -eq 0 ]; then
-		echo "WARNING: could not find copyright information for $f"
+		if ls -d vendor/$f >/dev/null 2>&1; then
+			found=$(find vendor/$f -iregex '.*LICENSE.*' -or -iregex '.*COPYRIGHT.*' -or -iregex '.*COPYING.*' | wc -l)
+			if [ $found -eq 0 ]; then
+				echo "WARNING: could not find copyright information for $f"
+			fi
+		else
+			echo "WARNING: $f is vendored but unused"
 		fi
-	else
-		echo "WARNING: $f is vendored but unused"
-	fi
 	done
 }
 
